version: '3'

services: 
  web:
    image: nginx
    ports: 
     - "8084:80"
  db: 
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: eureca_app
      MYSQL_USER: eureca
      MYSQL_PASSWORD: eureca@casal!
    ports:
      - "3306"
  app:
    build: .
    volumes:
      - ./rajadas-app:/eureca
    ports:
      - 3000:3000
    depends_on: 
      - db